# Generated by Django 5.1 on 2024-08-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postform',
            old_name='comment',
            new_name='message',
        ),
    ]
