# Generated by Django 5.1 on 2024-08-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='PostForm',
        ),
    ]
