# Generated by Django 5.1 on 2024-08-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_delete_coment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
