# Generated by Django 5.1 on 2024-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_blogpost_delete_postform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WriteNewPost',
            new_name='Posts',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
