# Generated by Django 5.0.8 on 2024-09-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile_userprofilerelatedposts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='relatedPosts',
        ),
    ]
