# Generated by Django 5.0.8 on 2024-09-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_userprofile_bio_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilerelatedposts',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofilerelatedposts',
            name='post',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfileRelatedPosts',
        ),
    ]
