# Generated by Django 5.1 on 2024-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
